version: '3'  

services: 
  express:
    build:
      context: .
      dockerfile: dockerfile/DockerFile.express
    ports:
      - 7000:8080
    depends_on:
      - db
  express-worker:
    image: express-prisma-express:latest
    command: bash -c "npx prisma migrate dev --name init && npm run worker"
    depends_on:
      - db
  db:
    container_name: postgresql
    image: postgres
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=accurate_temporal
  # mysql:
  #   image: mysql
  #   volumes:
  #     - db:/var/lib/mysql
  #   restart: on-failure
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234

volumes:
  db: