version: '3'  

services: 
  express:
    build:
      context: .
      dockerfile: dockerfile/DockerFile.express
    ports:
      - 7000:8080
    environment:
      - DATABASE_URL="mysql://root:1234@mysql:3306/accurate_temporal?schema=public"
      - PORT=8080
      - URL_TEMPORAL="host.docker.internal:7233"
      - ACCURATE_DB=1244837
      - ACCURATE_HOST=https://zeus.accurate.id
      - ACCURATE_API_KEY=ae07a555-1bc5-4195-b67b-a6fe39b858f0
      - ACCURATE_KEY=GXvV5sHWBkXZwYOnBmmcr6QhnVVeQy2Whu9Aa0ubZ66A0ONRPjzGYbKZbfR5hRuc
      - ACCURATE_TOKEN=aat.NTA.eyJ2IjoxLCJ1Ijo2NTczOTgsImQiOjEyNDQ4MzcsImFpIjo0NjEwMywiYWsiOiJhZTA3YTU1NS0xYmM1LTQxOTUtYjY3Yi1hNmZlMzliODU4ZjAiLCJhbiI6IlBPQy1XRUxMSU5HIiwiYXAiOiI4N2JiYTk2My1hYmFmLTQ0NTYtYWIxYy1jYTNkOWMzMTY1ZDUiLCJ0IjoxNzE0NjE5NTAyNDQzfQ.v0BhTi6WTCd5ZV+pywuvcow3SpWEbc29Mpn4touvN3WTNLTCo+Qh5Agj7SajtTbM4VOth14EiV9+EOdj9Cuk7VPEcK/ccx2687UJeQbBjSccVxGIvEoot9gxZpNKWQax4zvwml5XS9TkK6zx++K/nkMEQUy49alz88QkCgbBPN6qJKxZ5mY8NkMtO7UaM1Dehb32tONCMnU=.UFcbu099WPzDm/VG8gFnF2CasQT8ub/7r3dQLnKwvFQ
      - FRAPPE_HOST=https://dev-boat.tripwe.com
  express-worker:
    image: express-prisma-express:latest
    command: bash -c "npx prisma migrate dev --name init && npm run worker"
    environment:
      - DATABASE_URL="mysql://root:1234@mysql:3306/accurate_temporal?schema=public"
      - PORT=8080
      - URL_TEMPORAL="host.docker.internal:7233"
      - ACCURATE_DB=1244837
      - ACCURATE_HOST=https://zeus.accurate.id
      - ACCURATE_API_KEY=ae07a555-1bc5-4195-b67b-a6fe39b858f0
      - ACCURATE_KEY=GXvV5sHWBkXZwYOnBmmcr6QhnVVeQy2Whu9Aa0ubZ66A0ONRPjzGYbKZbfR5hRuc
      - ACCURATE_TOKEN=aat.NTA.eyJ2IjoxLCJ1Ijo2NTczOTgsImQiOjEyNDQ4MzcsImFpIjo0NjEwMywiYWsiOiJhZTA3YTU1NS0xYmM1LTQxOTUtYjY3Yi1hNmZlMzliODU4ZjAiLCJhbiI6IlBPQy1XRUxMSU5HIiwiYXAiOiI4N2JiYTk2My1hYmFmLTQ0NTYtYWIxYy1jYTNkOWMzMTY1ZDUiLCJ0IjoxNzE0NjE5NTAyNDQzfQ.v0BhTi6WTCd5ZV+pywuvcow3SpWEbc29Mpn4touvN3WTNLTCo+Qh5Agj7SajtTbM4VOth14EiV9+EOdj9Cuk7VPEcK/ccx2687UJeQbBjSccVxGIvEoot9gxZpNKWQax4zvwml5XS9TkK6zx++K/nkMEQUy49alz88QkCgbBPN6qJKxZ5mY8NkMtO7UaM1Dehb32tONCMnU=.UFcbu099WPzDm/VG8gFnF2CasQT8ub/7r3dQLnKwvFQ
      - FRAPPE_HOST=https://dev-boat.tripwe.com
  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql: