-- AlterTable
ALTER TABLE `sync_accurate_failed` MODIFY `type` ENUM('PRODUCT', 'SUPPLIER', 'PURCHASE_ORDER', 'PAYMENT_ENTRY') NOT NULL DEFAULT 'PRODUCT';

-- AlterTable
ALTER TABLE `sync_frappe_failed` MODIFY `type` ENUM('PRODUCT', 'SUPPLIER', 'PURCHASE_ORDER', 'PAYMENT_ENTRY') NOT NULL DEFAULT 'PRODUCT';
